[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:vault-kv-requirer-1
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-kv-requirer-b/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model         Controller                Cloud/Region        Version  SLA          Timestamp
test-kv-h7sj  github-pr-25e7f-microk8s  microk8s/localhost  3.6.9    unsupported  19:22:47Z

App                  Version  Status  Scale  Charm              Channel  Rev  Address         Exposed  Message
vault-k8s                     active      3  vault-k8s                     0  10.152.183.197  no       
vault-kv-requirer-a           active      1  vault-kv-requirer             0  10.152.183.19   no       
vault-kv-requirer-b           active      1  vault-kv-requirer             1  10.152.183.36   no       

Unit                    Workload  Agent  Address     Ports  Message
vault-k8s/0*            active    idle   10.1.22.81         
vault-k8s/1             active    idle   10.1.22.89         
vault-k8s/2             active    idle   10.1.22.88         
vault-kv-requirer-a/0*  active    idle   10.1.22.91         
vault-kv-requirer-b/0*  active    idle   10.1.22.93         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 19:19:07 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-h7sj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc039c3b380>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 19:19:09 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-h7sj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4e67674a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 19:19:09 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-h7sj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1a51c356a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 19:19:10 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-h7sj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f001b588530>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 19:19:11 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-h7sj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff37eac1d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 19:19:12 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-h7sj.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f851ddc5d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
model-98b6597a-6447-43db-8dec-1afb0c656f27: 19:21:17 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 19:21:23 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 19:21:23 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 19:21:23 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-kv-h7sj...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-a
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...