[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  self-signed-certificates/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
[32mINFO    [0m tests.integration.vault:vault.py:94 Unsealed vault unit: https://10.1.32.80:8200.
[32mINFO    [0m tests.integration.vault:vault.py:76 Vault unit is unsealed.
[32mINFO    [0m tests.integration.vault:vault.py:76 Vault unit is unsealed.
[32mINFO    [0m tests.integration.vault:vault.py:94 Unsealed vault unit: https://10.1.32.89:8200.
[32mINFO    [0m tests.integration.vault:vault.py:76 Vault unit is unsealed.
[32mINFO    [0m tests.integration.vault:vault.py:94 Unsealed vault unit: https://10.1.32.87:8200.
[32mINFO    [0m tests.integration.vault:vault.py:76 Vault unit is unsealed.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] blocked: Please unseal Vault
  vault-k8s/1 [idle] blocked: Please unseal Vault
  vault-k8s/2 [idle] blocked: Please unseal Vault
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model           Controller                Cloud/Region        Version  SLA          Timestamp
test-core-8oxx  github-pr-359b8-microk8s  microk8s/localhost  3.6.8    unsupported  15:00:19Z

App                       Version  Status  Scale  Charm                     Channel   Rev  Address        Exposed  Message
self-signed-certificates           active      1  self-signed-certificates  1/stable  317  10.152.183.43  no       
vault-k8s                          active      3  vault-k8s                             0  10.152.183.93  no       

Unit                         Workload  Agent  Address     Ports  Message
self-signed-certificates/0*  active    idle   10.1.32.95         
vault-k8s/0*                 active    idle   10.1.32.80         
vault-k8s/1                  active    idle   10.1.32.89         
vault-k8s/2                  active    idle   10.1.32.87         

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-vault-k8s-2: 14:52:21 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc0246b530>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 14:52:22 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa615ee7230>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 14:52:23 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe1b595f350>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 14:52:24 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f851af37380>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 14:52:24 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1e488eb260>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 14:52:25 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f43eff3f0b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 14:53:35 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f38afd68f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 14:54:21 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-a1234ac1-3b9a-49b5-8651-6fc37d181630: 14:54:21 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 14:54:21 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-3: 14:55:11 ERROR unit.vault-k8s/3.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2d7b156f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-3: 14:55:12 ERROR unit.vault-k8s/3.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7e1d37350>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-3: 14:55:13 ERROR unit.vault-k8s/3.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-3.vault-k8s-endpoints.test-core-8oxx.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b6673f170>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 14:57:05 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-a1234ac1-3b9a-49b5-8651-6fc37d181630: 14:57:06 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 14:57:06 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 14:57:06 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-self-signed-certificates-0: 14:59:50 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-self-signed-certificates-0: 14:59:51 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'
unit-self-signed-certificates-0: 15:00:09 ERROR unit.self-signed-certificates/0.juju-log At least 1 matching relation ID not found with the relation name 'send-ca-cert'

[32mINFO    [0m pytest_operator.plugin:plugin.py:1049 Resetting model test-core-8oxx...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications self-signed-certificates
[32mINFO    [0m pytest_operator.plugin:plugin.py:1054 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...