[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  loki-k8s/0 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model          Controller                Cloud/Region        Version  SLA          Timestamp
test-cos-sed1  github-pr-1b6c6-microk8s  microk8s/localhost  3.6.9    unsupported  11:49:20Z

App             Version  Status  Scale  Charm           Channel   Rev  Address         Exposed  Message
loki-k8s        2.9.6    active      1  loki-k8s        1/stable  199  10.152.183.64   no       
prometheus-k8s  2.52.0   active      1  prometheus-k8s  1/stable  247  10.152.183.63   no       
vault-k8s                active      3  vault-k8s                   0  10.152.183.241  no       

Unit               Workload  Agent  Address      Ports  Message
loki-k8s/0*        active    idle   10.1.242.95         
prometheus-k8s/0*  active    idle   10.1.242.94         
vault-k8s/0*       active    idle   10.1.242.80         
vault-k8s/1        active    idle   10.1.242.88         
vault-k8s/2        active    idle   10.1.242.90         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-1: 11:45:53 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-cos-sed1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f06f5e825d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 11:45:55 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-cos-sed1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc985a3b3b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 11:45:55 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-cos-sed1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff7980c5dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 11:45:57 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-cos-sed1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f46d47bdb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 11:45:57 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-cos-sed1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f950c62dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 11:46:05 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
model-dacbedeb-799a-413b-8155-9e6139f2c69f: 11:46:05 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 11:46:06 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 11:46:06 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-cos-sed1...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications prometheus-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications loki-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...