[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model                 Controller                Cloud/Region        Version  SLA          Timestamp
test-autounseal-quo1  github-pr-ca68b-microk8s  microk8s/localhost  3.6.8    unsupported  06:34:11Z

App        Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
vault-b             active      3  vault-k8s             0  10.152.183.102  no       
vault-k8s           active      3  vault-k8s             1  10.152.183.122  no       

Unit          Workload  Agent  Address      Ports  Message
vault-b/0*    active    idle   10.1.32.106         
vault-b/1     active    idle   10.1.32.104         
vault-b/2     active    idle   10.1.32.105         
vault-k8s/0*  active    idle   10.1.32.86          
vault-k8s/1   active    idle   10.1.32.92          
vault-k8s/2   active    idle   10.1.32.93          

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-vault-k8s-1: 06:28:10 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f919555b560>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:28:12 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49a7737170>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 06:28:13 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4bb957440>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 06:28:13 ERROR unit.vault-k8s/1.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d78f92ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 06:28:14 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f37a913eff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 06:28:15 ERROR unit.vault-k8s/2.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8843137350>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:20 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d2406f440>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:20 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bcfba38c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:21 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4c9cccd4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:22 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe4e047fb60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:23 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff660d45220>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:23 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efd50009550>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:24 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8d80aef860>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:25 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0671ff770>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:26 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6e16af52b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:26 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f867ccf8f20>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:27 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91364ef740>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:27 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3d3eef680>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:28 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83e07495e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:29 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9fd4a09340>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:30 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa383ac2ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:30 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fee746ef650>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:31 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f89bdb45250>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:32 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc2e8ef5460>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:31:33 ERROR unit.vault-b/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f20d1ceae10>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:31:34 ERROR unit.vault-b/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90a2412ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 06:32:38 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e0993f1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 06:33:05 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feec7b5d370>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 06:33:05 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efc73f49070>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 06:33:08 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-quo1.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7e6040f80>: Failed to establish a new connection: [Errno 111] Connection refused'))
model-2f9ea653-ea84-469f-83da-949ee5a896c5: 06:33:20 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 06:33:20 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 06:33:20 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 06:33:33 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1049 Resetting model test-autounseal-quo1...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications vault-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1038    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1054 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...