[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:vault-kv-requirer-1
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model         Controller                Cloud/Region        Version  SLA          Timestamp
test-kv-qagg  github-pr-a4dc2-microk8s  microk8s/localhost  3.6.9    unsupported  10:58:14Z

App                  Version  Status  Scale  Charm              Channel  Rev  Address         Exposed  Message
vault-k8s                     active      3  vault-k8s                     0  10.152.183.227  no       
vault-kv-requirer-a           active      1  vault-kv-requirer             0  10.152.183.18   no       
vault-kv-requirer-b           active      1  vault-kv-requirer             1  10.152.183.228  no       

Unit                    Workload  Agent  Address     Ports  Message
vault-k8s/0*            active    idle   10.1.72.80         
vault-k8s/1             active    idle   10.1.72.89         
vault-k8s/2             active    idle   10.1.72.88         
vault-kv-requirer-a/0*  active    idle   10.1.72.91         
vault-kv-requirer-b/0*  active    idle   10.1.72.93         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 10:54:05 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-qagg.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe88cb90c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 10:54:07 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-qagg.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f40424336e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 10:54:07 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-qagg.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe15a465a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 10:54:08 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-qagg.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd418d1b620>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 10:54:09 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-qagg.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f003f28a750>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 10:54:10 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-qagg.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fddc44436e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
model-40b3f432-9779-4cae-8c28-ce18cc6728fe: 10:56:21 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 10:56:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 10:56:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 10:56:25 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-kv-qagg...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-a
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...