[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model                 Controller                Cloud/Region        Version  SLA          Timestamp
test-autounseal-w0gl  github-pr-7271e-microk8s  microk8s/localhost  3.6.9    unsupported  07:31:47Z

App        Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
vault-b             active      3  vault-k8s             0  10.152.183.189  no       
vault-k8s           active      3  vault-k8s             1  10.152.183.201  no       

Unit          Workload  Agent  Address       Ports  Message
vault-b/0*    active    idle   10.1.113.170         
vault-b/1     active    idle   10.1.113.169         
vault-b/2     active    idle   10.1.113.168         
vault-k8s/0*  active    idle   10.1.113.149         
vault-k8s/1   active    idle   10.1.113.156         
vault-k8s/2   active    idle   10.1.113.157         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-1: 07:25:43 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f17638cd310>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 07:25:45 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe1873b97c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 07:25:45 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe946a41100>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 07:25:46 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4513610a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 07:25:46 ERROR unit.vault-k8s/1.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdee16612b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 07:25:48 ERROR unit.vault-k8s/2.juju-log vault-peers:1: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f86debaa300>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:11 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f12f68b88f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:12 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8dcb9ce6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:13 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f13d9c0f590>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:14 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef1d62d280>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:15 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f484ce59b20>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:16 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4ebd3574a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:17 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fea7cb597f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:18 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6a6b955610>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:19 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f85b213b530>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:21 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0b49370b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:21 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0fec65d850>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:23 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f052fe61610>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:23 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63ff8376b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:24 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdcd8dce240>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:25 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3dc1a3d9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:26 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e7945d850>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:27 ERROR unit.vault-b/1.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa100039be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:28 ERROR unit.vault-b/2.juju-log vault-autounseal-requires:2: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0a3b157020>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:29:29 ERROR unit.vault-b/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9cf7009370>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:29:30 ERROR unit.vault-b/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f498b709100>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 07:30:14 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b6d750950>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 07:30:41 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd3182c81a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 07:30:42 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde3f2dcfe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 07:30:42 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-autounseal-w0gl.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdd9a834740>: Failed to establish a new connection: [Errno 111] Connection refused'))
model-417a0cf8-4314-4643-8e5b-915bcf4f73c5: 07:30:48 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 07:30:48 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-b-2: 07:30:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 07:30:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: write tcp 10.1.113.149:59914->10.152.183.170:17070: write: connection reset by peer: write tcp 10.1.113.149:59914->10.152.183.170:17070: write: connection reset by peer
unit-vault-b-1: 07:30:53 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-b-0: 07:30:57 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 07:30:58 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-autounseal-w0gl...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...