[32mINFO    [0m juju.model:__init__.py:2301 Deploying local:vault-kv-requirer-1
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-k8s/0 [idle] active: 
  vault-k8s/1 [idle] active: 
  vault-k8s/2 [idle] active: 
  vault-kv-requirer-b/0 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  vault-kv-requirer-b/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:951 Model status:

Model         Controller                Cloud/Region        Version  SLA          Timestamp
test-kv-8ysu  github-pr-81ae1-microk8s  microk8s/localhost  3.6.9    unsupported  10:56:47Z

App                  Version  Status  Scale  Charm              Channel  Rev  Address         Exposed  Message
vault-k8s                     active      3  vault-k8s                     0  10.152.183.130  no       
vault-kv-requirer-a           active      1  vault-kv-requirer             0  10.152.183.102  no       
vault-kv-requirer-b           active      1  vault-kv-requirer             1  10.152.183.156  no       

Unit                    Workload  Agent  Address     Ports  Message
vault-k8s/0*            active    idle   10.1.22.87         
vault-k8s/1             active    idle   10.1.22.89         
vault-k8s/2             active    idle   10.1.22.88         
vault-kv-requirer-a/0*  active    idle   10.1.22.91         
vault-kv-requirer-b/0*  active    idle   10.1.22.93         

[32mINFO    [0m pytest_operator.plugin:plugin.py:957 Juju error logs:

unit-vault-k8s-2: 10:53:00 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-8ysu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3613b43050>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 10:53:02 ERROR unit.vault-k8s/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-8ysu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a310c1d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 10:53:03 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-8ysu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d9bb3f200>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-2: 10:53:04 ERROR unit.vault-k8s/2.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-2.vault-k8s-endpoints.test-kv-8ysu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a3ccc6930>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 10:53:05 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-8ysu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8c83c59d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-1: 10:53:06 ERROR unit.vault-k8s/1.juju-log vault-peers:0: [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-kv-8ysu.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcbcd8c1b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
model-5f9a3091-dfb7-485e-8960-2ce778f6d9fd: 10:55:24 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-1: 10:55:30 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-2: 10:55:30 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent
unit-vault-k8s-0: 10:55:30 ERROR juju.worker.dependency "log-sender" manifold worker returned unexpected error: sending log message: websocket: close 1005 (no status): websocket: close sent

[32mINFO    [0m pytest_operator.plugin:plugin.py:1063 Resetting model test-kv-8ysu...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-a
[32mINFO    [0m pytest_operator.plugin:plugin.py:1052    Destroying applications vault-kv-requirer-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1068 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1039 Forgetting model main...