{"uid":"beb4ceb0eea1d0c8","name":"test_given_vault_b_is_deployed_and_unsealed_when_auth_token_goes_bad_then_units_recover","fullName":"tests.integration.test_integration.TestVaultK8sIntegrationsPart3#test_given_vault_b_is_deployed_and_unsealed_when_auth_token_goes_bad_then_units_recover","historyId":"c3fb5b59ad370a3f16c5a959ca908035","time":{"start":1742489827809,"stop":1742489827809,"duration":0},"status":"broken","statusMessage":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 90, in pytest_runtest_setup\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 840, in pytest_runtest_setup\n    yield from self._runtest_for(item, \"setup\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 893, in pytest_runtest_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 87, in pytest_runtest_setup\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 160, in pytest_runtest_setup\n    item.session._setupstate.setup(item)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 514, in setup\n    col.setup()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1630, in setup\n    self._request._fillfixtures()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 697, in _fillfixtures\n    item.funcargs[argname] = self.getfixturevalue(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 532, in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 617, in _get_active_fixturedef\n    fixturedef.execute(request=subrequest)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1047, in execute\n    fixturedef = request._get_active_fixturedef(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 617, in _get_active_fixturedef\n    fixturedef.execute(request=subrequest)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1071, in execute\n    raise exc.with_traceback(exc_tb)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 323, in _async_fixture_wrapper\n    return event_loop.run_until_complete(setup())\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 320, in setup\n    res = await func(**_add_kwargs(func, kwargs, event_loop, request))\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/tests/integration/test_integration.py\", line 79, in deployed_vault\n    await ops_test.model.wait_for_idle(\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3245, in wait_for_idle\n    _raise_for_status(errors, \"error\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3136, in _raise_for_status\n    raise error_type(\njuju.errors.JujuUnitError: Unit in error: vault-k8s/0","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop","time":{"start":1742489771951,"stop":1742489771952,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1742489771952,"stop":1742489771952,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1742489771952,"stop":1742489772550,"duration":598},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"deployed_vault","time":{"start":1742489772550,"stop":1742489827759,"duration":55209},"status":"broken","statusMessage":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0\n","statusTrace":"  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 323, in _async_fixture_wrapper\n    return event_loop.run_until_complete(setup())\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 320, in setup\n    res = await func(**_add_kwargs(func, kwargs, event_loop, request))\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/tests/integration/test_integration.py\", line 79, in deployed_vault\n    await ops_test.model.wait_for_idle(\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3245, in wait_for_idle\n    _raise_for_status(errors, \"error\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3136, in _raise_for_status\n    raise error_type(\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 90, in pytest_runtest_setup\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 840, in pytest_runtest_setup\n    yield from self._runtest_for(item, \"setup\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 893, in pytest_runtest_setup\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 87, in pytest_runtest_setup\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 160, in pytest_runtest_setup\n    item.session._setupstate.setup(item)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 514, in setup\n    col.setup()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1630, in setup\n    self._request._fillfixtures()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 697, in _fillfixtures\n    item.funcargs[argname] = self.getfixturevalue(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 532, in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 617, in _get_active_fixturedef\n    fixturedef.execute(request=subrequest)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1047, in execute\n    fixturedef = request._get_active_fixturedef(argname)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 617, in _get_active_fixturedef\n    fixturedef.execute(request=subrequest)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1071, in execute\n    raise exc.with_traceback(exc_tb)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 323, in _async_fixture_wrapper\n    return event_loop.run_until_complete(setup())\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 320, in setup\n    res = await func(**_add_kwargs(func, kwargs, event_loop, request))\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/tests/integration/test_integration.py\", line 79, in deployed_vault\n    await ops_test.model.wait_for_idle(\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3245, in wait_for_idle\n    _raise_for_status(errors, \"error\")\n  File \"/home/ubuntu/actions-runner/_work/vault-k8s-operator/vault-k8s-operator/.tox/integration/lib/python3.10/site-packages/juju/model/__init__.py\", line 3136, in _raise_for_status\n    raise error_type(\njuju.errors.JujuUnitError: Unit in error: vault-k8s/0","steps":[],"attachments":[{"uid":"de14d2230faf2d9c","name":"log","source":"de14d2230faf2d9c.txt","type":"text/plain","size":1419}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"ops_test::finalizer","time":{"start":1742489827811,"stop":1742489831897,"duration":4086},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1742489831899,"stop":1742489831900,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1742489831900,"stop":1742489831900,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1742489831900,"stop":1742489831900,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_integration"},{"name":"subSuite","value":"TestVaultK8sIntegrationsPart3"},{"name":"host","value":"github-runner"},{"name":"thread","value":"42161-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_integration"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":2,"passed":9,"unknown":0,"total":13},"items":[{"uid":"7f685b08258eb0dd","reportUrl":"https://canonical.github.io/vault-k8s-operator/2858//#testresult/7f685b08258eb0dd","status":"passed","time":{"start":1742485363292,"stop":1742485376413,"duration":13121}},{"uid":"ca1d47316215c1fd","reportUrl":"https://canonical.github.io/vault-k8s-operator/2856//#testresult/ca1d47316215c1fd","status":"passed","time":{"start":1742481411931,"stop":1742481425607,"duration":13676}},{"uid":"775c20c5dfa2bdf0","reportUrl":"https://canonical.github.io/vault-k8s-operator/2855//#testresult/775c20c5dfa2bdf0","status":"passed","time":{"start":1742481224165,"stop":1742481237350,"duration":13185}},{"uid":"d49549c9e4ef3675","reportUrl":"https://canonical.github.io/vault-k8s-operator/2857//#testresult/d49549c9e4ef3675","status":"broken","statusDetails":"juju.errors.JujuUnitError: Unit in error: vault-k8s/0","time":{"start":1742481011678,"stop":1742481011678,"duration":0}},{"uid":"bbf222bcc6741ee8","reportUrl":"https://canonical.github.io/vault-k8s-operator/2853//#testresult/bbf222bcc6741ee8","status":"passed","time":{"start":1742476744426,"stop":1742476757975,"duration":13549}},{"uid":"828eec07d12b60ae","reportUrl":"https://canonical.github.io/vault-k8s-operator/2852//#testresult/828eec07d12b60ae","status":"passed","time":{"start":1742476732542,"stop":1742476745969,"duration":13427}},{"uid":"1f0dd70b61a00da2","reportUrl":"https://canonical.github.io/vault-k8s-operator/2851//#testresult/1f0dd70b61a00da2","status":"passed","time":{"start":1742475390953,"stop":1742475404442,"duration":13489}},{"uid":"25b70487195f8e38","reportUrl":"https://canonical.github.io/vault-k8s-operator/2850//#testresult/25b70487195f8e38","status":"passed","time":{"start":1742473356132,"stop":1742473369304,"duration":13172}},{"uid":"34ea71906ef3f9ca","reportUrl":"https://canonical.github.io/vault-k8s-operator/2849//#testresult/34ea71906ef3f9ca","status":"passed","time":{"start":1742472072063,"stop":1742472085406,"duration":13343}},{"uid":"778f656a6b40575a","reportUrl":"https://canonical.github.io/vault-k8s-operator/2848//#testresult/778f656a6b40575a","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1742470371961,"stop":1742470371961,"duration":0}},{"uid":"5d082a507def3141","reportUrl":"https://canonical.github.io/vault-k8s-operator/2846//#testresult/5d082a507def3141","status":"passed","time":{"start":1742468315402,"stop":1742468328760,"duration":13358}},{"uid":"a276516add56e38e","reportUrl":"https://canonical.github.io/vault-k8s-operator/2845//#testresult/a276516add56e38e","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1742430414467,"stop":1742430414467,"duration":0}}]},"tags":["asyncio","abort_on_fail"]},"source":"beb4ceb0eea1d0c8.json","parameterValues":[]}