[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  vault-b/0 [idle] active: 
  vault-b/1 [idle] active: 
  vault-b/2 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:929 Model status:

Model                  Controller                Cloud/Region        Version  SLA          Timestamp
test-integration-l0uz  github-pr-04333-microk8s  microk8s/localhost  3.6.1    unsupported  19:08:41Z

App        Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
vault-b             active      3  vault-k8s             1  10.152.183.230  no       
vault-k8s           active      3  vault-k8s             0  10.152.183.167  no       

Unit          Workload  Agent      Address     Ports  Message
vault-b/0*    active    executing  10.1.53.13         
vault-b/1     active    executing  10.1.53.4          
vault-b/2     active    executing  10.1.53.11         
vault-k8s/0*  active    executing  10.1.53.16         
vault-k8s/1   active    executing  10.1.53.25         
vault-k8s/2   active    executing  10.1.53.23         

[32mINFO    [0m pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-vault-k8s-1: 18:46:28 ERROR unit.vault-k8s/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-k8s-1.vault-k8s-endpoints.test-integration-l0uz.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x769ad0c9d030>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-k8s-3: 18:47:56 ERROR unit.vault-k8s/3.juju-log vault-peers:0: Raft cluster is not healthy. {'failure_tolerance': 1, 'healthy': False, 'leader': 'test-integration-l0uz-vault-k8s/0', 'servers': {'test-integration-l0uz-vault-k8s/0': {'id': 'test-integration-l0uz-vault-k8s/0', 'name': 'test-integration-l0uz-vault-k8s/0', 'address': 'vault-k8s-0.vault-k8s-endpoints.test-integration-l0uz.svc.cluster.local:8201', 'node_status': 'alive', 'last_contact': '0s', 'last_term': 3, 'last_index': 143, 'healthy': True, 'stable_since': '2025-01-17T18:42:25.211251158Z', 'status': 'leader', 'version': '1.16.3', 'node_type': 'voter'}, 'test-integration-l0uz-vault-k8s/1': {'id': 'test-integration-l0uz-vault-k8s/1', 'name': 'test-integration-l0uz-vault-k8s/1', 'address': 'vault-k8s-1.vault-k8s-endpoints.test-integration-l0uz.svc.cluster.local:8201', 'node_status': 'alive', 'last_contact': '2.582632505s', 'last_term': 3, 'last_index': 141, 'healthy': True, 'stable_since': '2025-01-17T18:43:27.211769336Z', 'status': 'voter', 'version': '1.16.3', 'node_type': 'voter'}, 'test-integration-l0uz-vault-k8s/2': {'id': 'test-integration-l0uz-vault-k8s/2', 'name': 'test-integration-l0uz-vault-k8s/2', 'address': 'vault-k8s-2.vault-k8s-endpoints.test-integration-l0uz.svc.cluster.local:8201', 'node_status': 'alive', 'last_contact': '2.623521266s', 'last_term': 3, 'last_index': 141, 'healthy': True, 'stable_since': '2025-01-17T18:43:29.211773022Z', 'status': 'voter', 'version': '1.16.3', 'node_type': 'voter'}, 'test-integration-l0uz-vault-k8s/3': {'id': 'test-integration-l0uz-vault-k8s/3', 'name': 'test-integration-l0uz-vault-k8s/3', 'address': 'vault-k8s-3.vault-k8s-endpoints.test-integration-l0uz.svc.cluster.local:8201', 'node_status': 'alive', 'last_contact': '64.813113ms', 'last_term': 0, 'last_index': 0, 'healthy': False, 'stable_since': '2025-01-17T18:47:55.211666991Z', 'status': 'non-voter', 'version': '1.16.3', 'node_type': 'voter'}}, 'voters': ['test-integration-l0uz-vault-k8s/0', 'test-integration-l0uz-vault-k8s/1', 'test-integration-l0uz-vault-k8s/2']}
controller-0: 19:03:08 ERROR juju.worker.caasunitprovisioner stopping application worker for minio: Operation cannot be fulfilled on statefulsets.apps "minio": StorageError: invalid object, Code: 4, Key: /registry/statefulsets/test-integration-l0uz/minio, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 9c91a06c-62b9-4066-ab97-0a791293be64, UID in object meta: 
unit-vault-b-0: 19:07:04 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-integration-l0uz.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x71a4c792ae90>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-1: 19:07:44 ERROR unit.vault-b/1.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-1.vault-b-endpoints.test-integration-l0uz.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7df2df1be0e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-2: 19:07:44 ERROR unit.vault-b/2.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-2.vault-b-endpoints.test-integration-l0uz.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7d69788278e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 19:07:47 ERROR unit.vault-b/0.juju-log [vault_client] Error while checking Vault health status: HTTPSConnectionPool(host='vault-b-0.vault-b-endpoints.test-integration-l0uz.svc.cluster.local', port=8200): Max retries exceeded with url: /v1/sys/health (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x713cd4b25f60>: Failed to establish a new connection: [Errno 111] Connection refused'))
unit-vault-b-0: 19:08:04 ERROR unit.vault-b/0.juju-log Raft cluster is not healthy. {'failure_tolerance': 0, 'healthy': False, 'leader': 'test-integration-l0uz-vault-b/1', 'servers': {'test-integration-l0uz-vault-b/0': {'id': 'test-integration-l0uz-vault-b/0', 'name': 'test-integration-l0uz-vault-b/0', 'address': 'vault-b-0.vault-b-endpoints.test-integration-l0uz.svc.cluster.local:8201', 'node_status': 'alive', 'last_contact': '4.783353ms', 'last_term': 0, 'last_index': 0, 'healthy': False, 'stable_since': '2025-01-17T19:08:03.054112191Z', 'status': 'voter', 'version': '1.16.3', 'node_type': 'voter'}, 'test-integration-l0uz-vault-b/1': {'id': 'test-integration-l0uz-vault-b/1', 'name': 'test-integration-l0uz-vault-b/1', 'address': 'vault-b-1.vault-b-endpoints.test-integration-l0uz.svc.cluster.local:8201', 'node_status': 'alive', 'last_contact': '0s', 'last_term': 4, 'last_index': 247, 'healthy': True, 'stable_since': '2025-01-17T19:08:03.054112191Z', 'status': 'leader', 'version': '1.16.3', 'node_type': 'voter'}, 'test-integration-l0uz-vault-b/2': {'id': 'test-integration-l0uz-vault-b/2', 'name': 'test-integration-l0uz-vault-b/2', 'address': 'vault-b-2.vault-b-endpoints.test-integration-l0uz.svc.cluster.local:8201', 'node_status': 'alive', 'last_contact': '4.782732ms', 'last_term': 0, 'last_index': 0, 'healthy': False, 'stable_since': '2025-01-17T19:08:03.054112191Z', 'status': 'voter', 'version': '1.16.3', 'node_type': 'voter'}}, 'voters': ['test-integration-l0uz-vault-b/1', 'test-integration-l0uz-vault-b/0', 'test-integration-l0uz-vault-b/2']}

[32mINFO    [0m pytest_operator.plugin:plugin.py:1041 Resetting model test-integration-l0uz...
[32mINFO    [0m pytest_operator.plugin:plugin.py:1030    Destroying applications vault-k8s
[32mINFO    [0m pytest_operator.plugin:plugin.py:1030    Destroying applications vault-b
[32mINFO    [0m pytest_operator.plugin:plugin.py:1046 Not waiting on reset to complete.
[32mINFO    [0m pytest_operator.plugin:plugin.py:1017 Forgetting model main...